{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "aa8cde64",
   "metadata": {
    "slideshow": {
     "slide_type": "slide"
    }
   },
   "source": [
    "# MSEE short course: Day 1 \n",
    "## RunModel\n",
    "https://uqpyproject.readthedocs.io/en/latest/runmodel_doc.html\n",
    "\n",
    "## Random variables\n",
    "https://uqpyproject.readthedocs.io/en/latest/distributions_doc.html#\n",
    "\n",
    "## Sampling methods\n",
    "https://uqpyproject.readthedocs.io/en/latest/samplemethods_doc.html"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d893d7ae",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Import some necessary libraries\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f903b13a",
   "metadata": {},
   "source": [
    "# Exercise - RunModel\n",
    "\n",
    "1. Link a $\\bf{Python}$ computational model with UQpy.The model consists in a highly nonlinear single degree of freedom system represented by a Bouc-Wen model of hysteresis:\n",
    "\n",
    "    \\begin{align*}\n",
    "    & m \\ddot{z}(t) + c \\dot{z}(t) + k r(t) = - \\ddot{u}(t) \\\\\n",
    "    & \\dot{r}(t) = \\dot{z} - \\beta \\vert\\dot{z}(t)\\vert \\vert r(t) \\vert^{n-1} r(t) - \\gamma \\dot{z}(t) \\vert r(t) \\vert^{n}\n",
    "    \\end{align*}\n",
    "\n",
    "    where $\\ddot{u}(t)$ is the ground motion (scaled el-centro earthquake ground motion) exciting the system (in $cm.s^2$). The system is parameterized by stiffness $k [cN/cm]$, damping $c$ and the parameters $r_{0}=\\sqrt[n]{\\frac{1}{\\beta-\\gamma}} [cm], \\delta=\\frac{\\beta}{\\beta+\\gamma}$ and $n$ of the Bouc-Wen model of hysteresis. Forward simulation of the problem is performed via a fourth-order Runge-Kutta method. The QoI consists of the displacement time-series  $z(t)$ and the reaction-force time-series $k\\cdot r(t)$ of the Bouc-Wen system (stored in a list). \n",
    "    \n",
    "    - Run the Bouc-wen model using the RunModel module of UQpy for the nominal set of parameters: $k=1.0$ [cN/cm], $r_{0}=2.5$ [cm], $\\delta=0.9$.\n",
    "\n",
    "    - Plot the Bouc-wen model response, i.e. $z(t)$ vs $k\\cdot r(t)$. \n",
    "\n",
    "\n",
    "    This example makes use of the following files:\n",
    "    - model.py contains the ``boucwen'' Python function that defines the computational Boucwen model.\n",
    "    - USACA47.035.txt contains a ground motion time series (El-Centro earthquake, downloaded from the Center for Engineering Strong Motion Data).\n",
    "\n",
    "\n",
    "2. Link a third-party software with UQpy. The model consists of an identation test performed on a cuboid sample with the aid an elastic contact sphere. \n",
    "\n",
    "    <img src=\"IndentationTest.png\" width=\"500\">\n",
    "\n",
    "   The analysis is performed with the aid of the python package $\\bf{sfepy}$. The model is described by the following equations, where the unknown quantity is the displacement field $\\bf{u}$: \n",
    "\n",
    "    \\begin{align*}\n",
    "    & \\int_{\\Omega}D_{ijkl}e_{ij}(v)e_{kl}(u) + \\int_{\\Gamma}v \\cdot f(d(u))n(u)=0 \\\\\n",
    "    where & \\\\\n",
    "    & D_{ijkl}=\\mu(\\delta_{ik}\\delta_{jl}+\\delta_{il}\\delta_{kl})+\\lambda \\delta_{ij}\\delta_{kl}\n",
    "    \\end{align*}\n",
    "    \n",
    "   This problem is described by even though composed by linear materials and described by small deformations, is highly non-linear due to the contact boundary conditions between the sphere and the cube. The system is parameterized by the elastic sphere stiffness parameter $k$ for positive penetration and force $f0$ for zero penetration. The QoI of the model consists of the displacement field produced by the identation test and specifically the maximum $\\bf{Z}$ displacement at the identation point. \n",
    "\n",
    "   - Change the **elastic_contact_sphere.py** script to accept input arguments from the UQpy RunModel module.\n",
    "    \n",
    "   - Run the sphere contact problem described above, as a third-party model, utilizing the RunModel module of Upy. The nominal values of the parameters [k, f0] are [1e5, 1e-2] equivalently.\n",
    "\n",
    "         This example makes use of the following files:\n",
    "          - elastic_contact_sphere.py contains the input parameters required for performing the analysis using ``sfepy'' package.\n",
    "          - simple.py contains the ``sfepy'' solver that executes the indentation test.\n",
    "          - PythonAsThirdParty_model.py contains the commands that execute the python sfepy model as a third-party party application.\n",
    "          - process_3rd_party_output.py contains the code required to post-process the output generated from the execution of the sfepy model.\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7a688b29",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-9ab3123cca2a>\", line 25, in <module>\n",
      "    model_serial_third_party=RunModel(model_script='PythonAsThirdParty_model.py',\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/UQpy/RunModel.py\", line 306, in __init__\n",
      "    self.parent_dir = os.getcwd()\n",
      "PermissionError: [Errno 1] Operation not permitted\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'PermissionError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/inspect.py\", line 1515, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/inspect.py\", line 1473, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/inspect.py\", line 737, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/inspect.py\", line 721, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/posixpath.py\", line 379, in abspath\n",
      "    cwd = os.getcwd()\n",
      "PermissionError: [Errno 1] Operation not permitted\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-9ab3123cca2a>\", line 25, in <module>\n",
      "    model_serial_third_party=RunModel(model_script='PythonAsThirdParty_model.py',\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/UQpy/RunModel.py\", line 306, in __init__\n",
      "    self.parent_dir = os.getcwd()\n",
      "PermissionError: [Errno 1] Operation not permitted\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'PermissionError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3458, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2063, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/inspect.py\", line 1515, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/inspect.py\", line 1473, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/inspect.py\", line 737, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/inspect.py\", line 721, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/posixpath.py\", line 379, in abspath\n",
      "    cwd = os.getcwd()\n",
      "PermissionError: [Errno 1] Operation not permitted\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-9ab3123cca2a>\", line 25, in <module>\n",
      "    model_serial_third_party=RunModel(model_script='PythonAsThirdParty_model.py',\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/UQpy/RunModel.py\", line 306, in __init__\n",
      "    self.parent_dir = os.getcwd()\n",
      "PermissionError: [Errno 1] Operation not permitted\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'PermissionError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3458, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2063, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2944, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3169, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3380, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2063, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/inspect.py\", line 1515, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/inspect.py\", line 1473, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/inspect.py\", line 737, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/inspect.py\", line 721, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/opt/anaconda3/envs/sfepy/lib/python3.8/posixpath.py\", line 379, in abspath\n",
      "    cwd = os.getcwd()\n",
      "PermissionError: [Errno 1] Operation not permitted\n"
     ]
    }
   ],
   "source": [
    "##Solution 1\n",
    "#from UQpy.RunModel import RunModel\n",
    "#boucwen = RunModel(model_script='model.py', model_object_name='boucwen', \n",
    "#                           var_names=['k', 'r0', 'delta'])\n",
    "\n",
    "#import numpy as np\n",
    "#samples = np.array([1.0, 2.5, 0.9]).reshape((1, 3))\n",
    "#boucwen.run(samples=samples)\n",
    "#qoi = boucwen.qoi_list\n",
    "\n",
    "#plt.figure()\n",
    "#plt.plot(qoi[0][0], qoi[0][1])\n",
    "#plt.xlabel('displacement $z(t) \\quad [cm]$', fontsize=12) \n",
    "#plt.ylabel(r'reaction force $k r(t) \\quad [cN]$', fontsize=12); \n",
    "#plt.title('Bouc-Wen model response', fontsize=14)\n",
    "#plt.tight_layout()\n",
    "#plt.show()\n",
    "\n",
    "## Solution 2\n",
    "import numpy as np\n",
    "from UQpy.RunModel import RunModel\n",
    "\n",
    "samples = np.array([1e5, 1e-2]).reshape((1, 2))\n",
    "\n",
    "model_serial_third_party=RunModel(model_script='PythonAsThirdParty_model.py',\n",
    "    input_template='elastic_contact_sphere.py', var_names=['k', 'f0'],\n",
    "    output_script='process_3rd_party_output.py', model_object_name='read_output', delete_files=True)\n",
    "\n",
    "model_serial_third_party.run(samples=samples)\n",
    "\n",
    "qoi = model_serial_third_party.qoi_list"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "aae1eafb",
   "metadata": {
    "slideshow": {
     "slide_type": "slide"
    }
   },
   "source": [
    "# Exercise 2 - Random variables\n",
    "\n",
    "Random variable $X$ is normally distributed with mean $\\mu=5.0$ and standard deviation $\\sigma=0.2$. Define an 1d continuous distrbution distribution object for this random variable using the $\\bf{Distributions}$ module in UQpy.\n",
    "\n",
    "- Compute the $cdf$, $pdf$ and $log\\_pdf$ of $X$. Plot the three functions.\n",
    "\n",
    "- Modify the $loc$ parameter of the distribution, i.e., set it equal to 50.0. Calculate and plot the $cdf$, $pdf$ and $log\\_pdf$ of the modified lognormal distribution.\n",
    "\n",
    "- Print the first four $central$ $moments$ of the distribution, i.e., mean, standard deviation, skewness, kyrtosis.\n",
    "\n",
    "- Given the  list [4, 2, 2, 1]  that contains measurements of $X$, what are the parameters $loc$, $scale$,  of the Normal distribution? What is the parameter $scale$ if $loc=1.5$?\n",
    "\n",
    "- Consider the random variable $Z_i$, $i=1, ...,4$ that follow the Normal distribution $N(0, 1)$. Create a joint distribution as a product of four independent univariate distributions $Z_i$. \n",
    "\n",
    "$\\bf{Note}$: UQpy offers the capability to build a custom  distribution. You will need to create a child class of DistributionND parent class and, define the necessasry methods. Next, we have an example of using the $\\bf{Rosenbrock}$ function as the target $\\bf{pdf}$.\n",
    "\n",
    "    from UQpy.Distributions import DistributionND\n",
    "\n",
    "    class custom_name(DistributionND):\n",
    "        def __init__(self, p=20.):\n",
    "            super().__init__(p=p)\n",
    "        def pdf(self, x):\n",
    "            return np.exp(-(100*(x[:, 1]-x[:, 0]**2)**2+(1-x[:, 0])**2)/self.params['p'])\n",
    "        def log_pdf(self, x):\n",
    "            return -(100*(x[:, 1]-x[:, 0]**2)**2+(1-x[:, 0])**2)/self.params['p']\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2a3f42da",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "f902f027",
   "metadata": {},
   "source": [
    "# Exercise 3 - Forward UQ \n",
    "\n",
    "In this example you have to propagate uncertainties through a python and a third-party computational model. Samples of the input uncertainties are obtained via Monte Carlo sampling  and Latin Hypercube sampling - see $\\bf{SampleMethods}$ module in UQpy.  \n",
    "\n",
    "1. In the $\\bf{Boucwen}$ model randomness is assumed in the systems' parameters [$k, r_{0}, \\delta$] (assuming no damping, $c=0$). Parameter $k$ is assumed to be uniformly distributed between 0.5 cN/cm and 2.5 cN/cm. Parameter $r_{0}$ is assumed to be normally distributed, with the parameters being: $\\mu=2.5$ cm and standard deviation $\\sigma=0.4$.  Parameter $\\delta$ is assumed to be lognormally distributed, with the parameters of the underlying Gaussian distribution being: $\\mu$ = 0.9 and standard deviation $\\sigma=0.2$.  The parameters of the lognormal distribution in this case are $s=0.198$ and $scale=0.882$ ($loc$=0.0). Generate 50 realizations of the parameters and propagate them through the model to estimate the cooresponding response. In this case,we are interested in the maximum value of the reaction force (needs to be extracted from the QoI from the model).\n",
    "\n",
    "    This example makes use of the following files:\n",
    "    - model.py contains the ``boucwen'' Python function that defines the computational Boucwen model.\n",
    "    - USACA47.035.txt contains a ground motion time series (El-Centro earthquake, downloaded from the Center for Engineering Strong Motion Data).\n",
    "    \n",
    "    \n",
    " 2. Propagate  input parameter uncertainties through the third-party computational $\\bf{sfepy}$ contact sphere model. In the indentation test model randomness is assumed in the parameters [$k, f0$]. Parameter $k$ is assumed to follow a Lognormal distribution with the parameters of the underlying Gaussian distribution being: $\\mu$ = 1e5 and standard deviation $\\sigma=2e4$. Parameter $f0$ is assumed to follow a uniform distribution in the range [1e-2, 1e-1]. The parameters of the lognormal distribution in this case are $s=???$ and $scale=????$ ($loc$=0.0). Generate 10 realizations of the parameters and propagate them through the model to estimate the cooresponding response.In this case, we are interested in the maximum displacement at the identation point.\n",
    " \n",
    "    This example makes use of the following files:\n",
    "    - elastic_contact_sphere.py contains the input parameters required for performing the analysis using $\\bf{sfepy}$ package.\n",
    "    - simple.py contains the $\\bf{sfepy}$ solver that executes the indentation test.\n",
    "    - PythonAsThirdParty_model.py contains the commands that execute the python sfepy model as a third-party party application.\n",
    "    - process_3rd_party_output.py contains the code required to post-process the output generated from the execution of the sfepy model."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c57fa712",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Solution 3.1\n",
    "#from UQpy.RunModel import RunModel\n",
    "#from UQpy.SampleMethods import MCS\n",
    "#from UQpy.Distributions import Normal, Uniform, Lognormal, JointInd\n",
    "\n",
    "## Define distribution objects\n",
    "#dist1 = Uniform(loc=0.5, scale=2.0)\n",
    "#dist2 = Normal(loc=2.5, scale=0.25)\n",
    "#dist3 = Lognormal(s=0.198, scale=0.882)\n",
    "#dist = JointInd(marginals=[dist1, dist2, dist3])\n",
    "\n",
    "## Generate samples with MCS\n",
    "#samples=MCS(dist_object=dist, nsamples=5).samples\n",
    "\n",
    "##Run the model\n",
    "#boucwen = RunModel(model_script='model.py', model_object_name='boucwen_sdof', \n",
    "#                           var_names=['k', 'r0', 'delta'])\n",
    "#boucwen.run(samples=samples)\n",
    "#qoi = boucwen.qoi_list\n",
    "\n",
    "#import matplotlib.pyplot as plt\n",
    "#plt.figure()\n",
    "#plt.plot(qoi[0][0], qoi[0][1])\n",
    "#plt.plot(qoi[1][0], qoi[1][1])\n",
    "#plt.xlabel('displacement $z(t) \\quad [cm]$', fontsize=12) \n",
    "#plt.ylabel(r'reaction force $k r(t) \\quad [cN]$', fontsize=12); \n",
    "#plt.title('Bouc-Wen model response', fontsize=14)\n",
    "#plt.tight_layout()\n",
    "#plt.show()\n",
    "\n",
    "#Solution 3.2\n",
    "#import numpy as np\n",
    "#from UQpy.RunModel import RunModel\n",
    "#from UQpy.SampleMethods import MCS\n",
    "#from UQpy.Distributions import Uniform\n",
    "\n",
    "#dist1 = Uniform(loc=0.9*1e5, scale=0.2*1e5)\n",
    "#dist2 = Uniform(loc=1e-2, scale=1e-1)\n",
    "\n",
    "#x = MCS(dist_object=[dist1,dist2], nsamples=2, random_state=np.random.RandomState(1821),  verbose=True)\n",
    "#samples = x.samples\n",
    "\n",
    "#model_serial_third_party=RunModel(samples=samples,  model_script='PythonAsThirdParty_model.py',\n",
    "#    input_template='elastic_contact_sphere.py', var_names=['k', 'f0'],\n",
    "#    output_script='process_3rd_party_output.py', model_object_name='read_output', delete_files=True)\n",
    "\n",
    "#qoi = model_serial_third_party.qoi_list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7ef1dcf1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "celltoolbar": "Slideshow",
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
